config:
  language: 'pt-BR'
  # in seconds - default = 1800 (30min)
  vip-expiration-check-interval: 1800
  prefix: '&6[CelestialVIP]'
  announce:
    active: true
    # types: chat, actionbar, title
    type: 'chat'
    title:
      title: '%player% se tornou um'
      subtitle: '%tag%'
    chat-and-actionbar:
      message: '&a%player% se tornou um %tag%'
  key-size: 15
  database:
    # 'mysql' , 'postgresql' or 'sqlite'
    drive: 'sqlite'
    host: 'localhost'
    port: '3306'
    database: 'teste'
    user: 'root'
    password: 'password'
    tb_prefix: 'celestialvip_'
  mercadopago:
    CLIENT_ID: 'CLIENT_ID'
    CLIENT_SECRET: 'CLIENT_SECRET'
  #
  #   [console] = comando é executado pelo console.
  #   [player] = comando é executado pelo player.
  #   [message] = mensagem é enviada para o player.
  #   [sound] = reproduz o som especifico.
  #   %player% = o nome do jogador aparecerá no lugar.
  #   %tag% = tag do vip escolhida aparecerá no lugar.
  #   %group% = nome do grupo vip escolhido aparecerá no lugar.
  #   %days% = quantidade de dias vip aparece no lugar.
  #   %value% = quantidade de cash aparecerá no lugar.
  #
  vips:
    diamond:
      tag: '&bVIP DIAMOND'
      after-expiration-commands:
        - '[console] lp user %player% parent remove %group%'
      activation-commands:
        - '[console] lp user %player% parent add %group%'
        - '[console] give %player% netherite_sword 1'
        - '[console] give %player% netherite_helmet 1'
        - '[console] give %player% netherite_chestplate 1'
        - '[console] give %player% netherite_leggings 1'
        - '[console] give %player% netherite_boots 1'
        - '[console] eco give %player% 1000'
        - '[sound] ENTITY_PLAYER_LEVELUP'
    #
    gold:
      tag: '&eVIP GOLD'
      after-expiration-commands:
        - '[console] lp user %player% parent remove %group%'
      activation-commands:
        - '[console] lp user %player% parent add %group%'
        - '[console] give %player% netherite_sword 1'
        - '[console] give %player% netherite_helmet 1'
        - '[console] give %player% netherite_chestplate 1'
        - '[console] give %player% netherite_leggings 1'
        - '[console] give %player% netherite_boots 1'
        - '[console] eco give %player% 500'
        - '[sound] ENTITY_PLAYER_LEVELUP'
    #
    iron:
      tag: '&2VIP IRON'
      after-expiration-commands:
        - '[console] lp user %player% parent remove %group%'
      activation-commands:
        - '[console] lp user %player% parent add %group%'
        - '[console] give %player% netherite_sword 1'
        - '[console] give %player% netherite_helmet 1'
        - '[console] give %player% netherite_chestplate 1'
        - '[console] give %player% netherite_leggings 1'
        - '[console] give %player% netherite_boots 1'
        - '[console] eco give %player% 100'
        - '[sound] ENTITY_PLAYER_LEVELUP'
  #
  # Use %value% como parametro para a quantidade de cash.
  cash:
    activation-commands:
      - '[console] cash set %player% %value%'
      - '[message] voce comprou %value% em cash'
      - '[sound] ENTITY_PLAYER_LEVELUP'
