name: CelestialVIP
version: '${project.version}'
main: br.com.celestialvip.CelestialVIP
api-version: 1.19
commands:
  celestialvip:
    description: Recarrega o CelestialVIP.
    usage: /celestialvip reload
    permission: celestialvip.reload
    aliases: [ cv, celestial-vip ]
  gerarchavevip:
    description: Gera uma chave de ativação do vip escolhido.
    usage: /gerarchavevip <vip> <dias>.
    permission: celestialvip.adm
    aliases: [ generatevipkey ]
  resgatarvip:
    description: resgata seu vip usando o codigo da compra.
    usage: /resgatarvip <id da transação>
    aliases: [ redeemvip ]
  resgatarcash:
    description: resgata seu cash usando o codigo da compra.
    usage: /resgatarcash <id da transação>.
    aliases: [ redeemcash ]

