name: CelestialVIP
version: '${project.version}'
main: br.com.celestialvip.CelestialVIP
api-version: 1.19
commands:
  celestialvip:
    description: Recarrega o CelestialVIP.
    usage: /celestialvip reload
    permission: celestialvip.reload
    aliases: [ cv, celestial-vip ]
  gerarchave:
    description: Gera uma chave de ativação do vip escolhido.
    usage: |
      /gerarchave vip <grupo> <dias>.
      /gerarchave cash <quantidade>.
    permission: celestialvip.adm
    aliases: [ generatekey ]
  resgatar:
    description: resgata seu vip/cash usando o codigo da compra.
    usage: /resgatar [vip/cash] <id da transação>
    aliases: [ redeem ]
  usarchave:
    description: usa uma chave vip existente.
    usage: /usarchave [vip/cash] <chave>.
    aliases: [ usekey ]
  listarchaves:
    description: lista chaves vips/cash existentes.
    usage: /listarchaves [vip/cash].
    permission: celestialvip.adm
    aliases: [ listkeys ]

